name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - latest
  schedule:
    # "At 02:00 on Monday" https://crontab.guru/#0_2_*_*_1
    - cron: "0 2 * * 1"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup git user
        run: |
          git config --global user.email "ops+robot@npmjs.com"
          git config --global user.name "npm team"
      - uses: ./.github/workflows/partials/setup-node
        with:
          node-version: 16.x
          os: ubuntu-latest
      - run: npm i --ignore-scripts --no-audit --no-fund
      - run: npm run lint
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12.13.0
          - 12.x
          - 14.15.0
          - 14.x
          - 16.0.0
          - 16.x
        platform:
          - os: ubuntu-latest
            shell: bash
          - os: macos-latest
            shell: bash
          - os: windows-latest
            shell: cmd
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/partials/setup-node
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.platform.os }}
      - run: |
          pwd
          ls
      - run: npm i --ignore-scripts --no-audit --no-fund
      - run: npm test --ignore-scripts
