name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - latest
  schedule:
    # "At 02:00 on Monday" https://crontab.guru/#0_2_*_*_1
    - cron: "0 2 * * 1"

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
