name: eslint
on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ''

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: ./.github/workflows/partials/setup-node
        with:
          node-version: 16.x
      - run: npm i --ignore-scripts --no-audit --no-fund
      - run: npm run lint
      - name: Create check run
        if: ${{ inputs.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo '${{ toJSON(github) }}'
          echo '${{ toJSON(job) }}'
          gh api /repos/{owner}/{repo}/check-runs \
            -f name="lint" \
            -f head_sha="${{ inputs.ref }}" \
            -f status=completed \
            -f conclusion="${{ job.status }}"
