name: eslint
on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ''

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: ./.github/workflows/partials/setup-node
        with:
          node-version: 16.x
      - run: npm i --ignore-scripts --no-audit --no-fund
      - run: npm run lint
      - name: Create check run
        if: ${{ inputs.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CHECKSUITE_ID=$(gh api /repos/{owner}/{repo}/actions/runs/${{ github.run_id }} --jq .check_suite_id)
          echo $CHECKSUITE_ID
          gh api "/repos/{owner}/{repo}/check-suites/$CHECKSUITE_ID/check-runs?check_name=lint%20%2f%20lint"
          echo "******************"
          echo "******************"
          echo "******************"
          gh api /repos/{owner}/{repo}/check-runs \
            -f name="lint" \
            -f head_sha="${{ inputs.ref }}" \
            -f status=completed \
            -f conclusion="${{ job.status }}" \
            -f details_url="$(gh api /repos/{owner}/{repo}/actions/runs/${{ github.run_id }} --jq .html_url)"
