name: matrix testing ${{ inputs.nodeVersion }}

on:
  workflow_dispatch:
    inputs:
      nodeVersion:
        type: string
        default: "nightly"
        required: true

jobs:
  build:
    id: build-${{ inputs.nodeVersion }}
    name: build ${{ inputs.nodeVersion }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "18"
          - "19"
          - "nightly"
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
      - name: build
        run: |
          FINAL_VERSION="${{ matrix.version }}.$(date +%s)"

          echo "version=$FINAL_VERSION" >> $GITHUB_OUTPUT
