name: Rebase Merge

on:
  issue_comment:
    types:
      - created

permissions:
  contents: write

jobs:
  merge:
    name: Rebase Merge
    if: ${{ github.event.issue.pull_request && github.event.comment.author_association == 'OWNER' && startsWith(github.event.comment.body, '@npm-cli-bot rebase merge') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Rebase
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email "npm-cli+bot@github.com"
          git config --global user.name "npm CLI robot"

          PR_NUMBER=$(gh api '${{ github.event.issue.pull_request.url }}' -q .number)
          BASE_REF=$(gh api '${{ github.event.issue.pull_request.url }}' -q .base.ref)
          PR_REF=$(gh api '${{ github.event.issue.pull_request.url }}' -q .head.ref)
          echo "gh pr checkout $PR_NUMBER"
          gh pr checkout "$PR_NUMBER"
          echo "git checkout $BASE_REF"
          git checkout "$BASE_REF"
          echo "git merge $PR_REF --ff-only"
          git merge "$PR_REF" --ff-only
          echo "git push"
          git push
