name: Rebase Merge

on:
  issue_comment:
    types:
      - created

jobs:
  merge:
    name: Rebase Merge
    if: ${{ github.event.issue.pull_request && github.event.comment.author_association == 'OWNER' && startsWith(github.event.comment.body, '@npm-cli-bot rebase merge') }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine git ref
        id: ref
        run: |
          REF=$(gh api '${{ github.event.issue.pull_request.url }}' -q .head.ref)
          echo "ref=$REF" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.ref.outputs.ref }}
      - name: Rebase
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git status

