name: Rebase Merge

on:
  issue_comment:
    types:
      - created

jobs:
  merge:
    name: Rebase Merge
    if: ${{ github.event.issue.pull_request && github.event.comment.author_association == 'OWNER' }}
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo 'got comment from an owner: ${{ github.event.comment.body }}'
