name: Merge

on:
  issue_comment:
    types:
      - created

permissions:
  contents: write

jobs:
  merge:
    name: Merge
    if: ${{ github.event.issue.pull_request && github.event.comment.author_association == 'OWNER' && startsWith(github.event.comment.body, '@npm-cli-bot merge') }}
    runs-on: ubuntu-latest
    steps:
      - name: Gather metadata
        id: metadata
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # retrieve some data from the pull request
          PR_META=$(gh api '${{ github.event.issue.pull_request.url }}' -q '{ number: .number, base: .base.ref, head: .head.ref }')
          PR_NUMBER=$(echo "$PR_META" | jq -r .number)
          HEAD_REF=$(echo "$PR_META" | jq -r .head)
          BASE_REF=$(echo "$PR_META" | jq -r .base)

          echo "number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "head=$HEAD_REF" >> $GITHUB_OUTPUT
          echo "base=$BASE_REF" >> $GITHUB_OUTPUT
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          ref: ${{ steps.metadata.outputs.base }}
      - name: Merge
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # configure the git user
          git config --global user.email "npm-cli+bot@github.com"
          git config --global user.name "npm CLI robot"

          gh pr checkout "${{ steps.metadata.outputs.number }}"
          git rebase --onto "${{ steps.metadata.outputs.base }}..." "${{ steps.metadata.outputs.base }}"
          git checkout "${{ steps.metadata.outputs.base }}"
          git merge "${{ steps.metadata.outputs.head }}" --ff-only
          git push
