name: release integration

on:
  release:
    type:
      - published
  workflow_dispatch:
    inputs:
      npmVersion:
        description: npm version to test
        type: string
        required: true

jobs:
  node-integration:
    env:
      npmVersion: ${{ inputs.npmVersion || github.ref_name }}
    name: nodejs@${{ matrix.nodeVersion }} integration
    if: ${{ startsWith(github.ref_name, 'v') }}
    strategy:
      matrix:
        nodeVersion:
          - 18
          - 19
          - nightly
    uses: ./.github/workflows/node-integration.yml
    with:
      nodeVersion: ${{ matrix.nodeVersion }}
      npmVersion: ${{ env.npmVersion }}

