name: release integration

on:
  release:
    type:
      - published
  workflow_dispatch:
    inputs:
      npmVersion:
        description: npm version to test
        type: string
        required: true

jobs:
  node-integration:
    name: nodejs@${{ matrix.nodeVersion }} integration
    if: ${{ inputs.npmVersion || startsWith(github.ref_name, 'v') }}
    env:
      npmVersion: ${{ inputs.npmVersion || github.ref_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeVersion:
          - 18
          - 19
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: clean npm version
        id: version
        run: |
          npmVersion="${{ env.npmVersion }}"
          npmVersion="${npmVersion/#v}"
          echo "npmVersion=${npmVersion}" >> $GITHUB_OUTPUT
      - name: nodejs@${{ matrix.nodeVersion }} npm@${{ steps.version.outputs.npmVersion }}
        uses: ./.github/workflows/node-integration.yml
        with:
          nodeVersion: ${{ matrix.nodeVersion }}
          npmVersion: ${{ steps.version.outputs.npmVersion }}

