name: release integration

on:
  release:
    types: [published]
  workflow_call:
    inputs: &inputs
      npmVersion:
        description: npm version to test
        type: string
        required: true
      pullRequest:
        description: pull request number
        type: string
        required: false
  workflow_dispatch:
    inputs: *inputs

jobs:
  pr-comment:
    name: add comment to pull request
    if: ${{ inputs.pullRequest }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: add comment
        run: |
          set +e
          gh pr comment ${{ inputs.pullRequest }} \
            --edit-last \
            --repo '${{ github.repository }}' \
            --body "citgm: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          if [[ $? -ne 0 ]]; then
            set -e
            gh pr comment ${{ inputs.pullRequest }} \
              --repo '${{ github.repository }}' \
              --body "citgm: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          fi

  node-integration:
    name: nodejs@${{ matrix.nodeVersion }} integration
    strategy:
      fail-fast: false
      matrix:
        nodeVersion:
          - 18
          - 19
          - nightly
    uses: ./.github/workflows/node-integration.yml
    with:
      nodeVersion: ${{ matrix.nodeVersion }}
      npmVersion: ${{ inputs.npmVersion }}

