name: release

on:
  workflow_call:
    inputs:
      version:
        description: 'version to release'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: 'version to release'
        required: true
        type: string

jobs:
  release:
    name: publish release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: publish release
        run: |
          gh release create ${{ inputs.version }} --title ${{ inputs.version }} --notes 'release ${{ inputs.version }}' --repo '${{ github.repository }}'

  integration:
    name: integration test
    needs: [release]
    uses: ./.github/workflows/release-integration.yml
    with:
      npmVersion: ${{ inputs.version }}
      pullRequest: "2"
