name: release integration

on:
  release:
    types: [published]
  workflow_call:
    inputs:
      npmVersion:
        description: npm version to test
        type: string
        required: true
      pullRequest:
        description: pull request number
        type: string
        required: false
  workflow_dispatch:
    inputs:
      npmVersion:
        description: npm version to test
        type: string
        required: true
      pullRequest:
        description: pull request number
        type: string
        required: false

jobs:
  # pr-comment:
  #   name: add comment to pull request
  #   if: ${{ inputs.pullRequest }}
  #   steps:
  #     - name: add comment
  #       run: |
  #         gh pr comment ${{ inputs.pullRequest }} --edit-last --body "citgm: ${{ github.server_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}"

  node-integration:
    name: nodejs@${{ matrix.nodeVersion }} integration
    strategy:
      fail-fast: false
      matrix:
        nodeVersion:
          - 18
          - 19
          - nightly
    uses: ./.github/workflows/node-integration.yml
    with:
      nodeVersion: ${{ matrix.nodeVersion }}
      npmVersion: ${{ inputs.npmVersion }}

