name: test
on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ''

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 12.13.0
          - 12.x
          - 14.15.0
          - 14.x
          - 16.0.0
          - 16.x
        platform:
          - os: ubuntu-latest
            shell: bash
          - os: macos-latest
            shell: bash
          - os: windows-latest
            shell: cmd
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: ./.github/workflows/partials/setup-node
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.platform.os }}
          shell: ${{ matrix.platform.shell }}
      - run: npm i --ignore-scripts --no-audit --no-fund
      - run: npm test --ignore-scripts

