name: test
on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ''

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16.x
        platform:
          - os: ubuntu-latest
            shell: bash
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: ./.github/workflows/partials/setup-node
        with:
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.platform.os }}
          shell: ${{ matrix.platform.shell }}
      - run: npm i --ignore-scripts --no-audit --no-fund
      - run: npm test --ignore-scripts
      - name: Create check run
        if: ${{ inputs.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api /repos/{owner}/{repo}/check-runs \
            -f name="test (${{ matrix.node-version }}, ${{ matrix.platform.os }}, ${{ matrix.platform.shell }})" \
            -f head_sha="${{ inputs.ref }}" \
            -f status=completed \
            -f conclusion="${{ job.status }}"
