name: Update a thing

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.status.outputs.has-changes }}
      commit-ref: ${{ steps.commit.outputs.commit-ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Maybe make some changes
        id: commit
        run: |
          if [[ $((RANDOM%2)) -eq 1 ]]; then
            echo "t.pass('ran again')" >> test/index.js
          fi
      - name: Check for changes
        id: status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=has-changes::true"
          fi
      - name: Commit and push changes
        if: steps.status.outputs.has-changes == 'true'
        run: |
          git add test/index.js
          git config --local user.email "ops+npm-cli@npmjs.com"
          git config --local user.name "npm cli ops bot"
          git commit -m 'chore: add a test'
          git push origin main
          echo "::set-output name=commit-ref::$(git rev-parse HEAD)"

  test:
    needs: update
    if: needs.update.outputs.has-changes == 'true'
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ needs.update.outputs.commit-ref }}
