name: Update a thing

on:
  workflow_dispatch:

permissions:
  contents: write
  checks: write

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.status.outputs.has-changes }}
      commit-ref: ${{ steps.commit.outputs.commit-ref }}
      check-id: ${{ steps.create-run.outputs.script-result }}
    steps:
      - uses: actions/checkout@v3
      - name: Maybe make some changes
        run: |
          if [[ $((RANDOM%2)) -eq 1 ]]; then
            echo "t.pass('ran again')" >> test/index.js
          fi
      - name: Check for changes
        id: status
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::set-output name=has-changes::true"
          fi
      - name: Commit and push changes
        id: commit
        if: steps.status.outputs.has-changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.pull_request.number }}
          git add test/index.js
          git config --local user.email "ops+npm-cli@npmjs.com"
          git config --local user.name "npm cli ops bot"
          git commit -m 'chore: add a test'
          git push
          echo "::set-output name=commit-ref::$(git rev-parse HEAD)"
      - name: Create check run for future commit
        id: create-run
        if: steps.status.outputs.has-changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./.github/workflows/steps/run-node-script
        with:
          path: ./.github/scripts
          script: create-check-run
          args: |
            --repository=${{ github.repository }} \
            --head_sha=${{ steps.commit.outputs.commit-ref }} \
            --name="Running post-modification actions" \
            --status=in_progress

  lint:
    needs: update
    if: needs.update.outputs.has-changes == 'true'
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ needs.update.outputs.commit-ref }}

  test:
    needs: update
    if: needs.update.outputs.has-changes == 'true'
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ needs.update.outputs.commit-ref }}

  create-run:
    if: ${{ needs.update.outputs.has-changes == 'true' }}
    needs:
      - update
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy check runs
        id: copy-runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./.github/workflows/steps/run-node-script
        with:
          path: ./.github/scripts
          script: copy-check-runs
          args: |
            --repository=${{ github.repository }} \
            --run_id=${{ github.run_id }} \
            --head_sha=${{ needs.update.outputs.commit-ref }}
      - name: Update pending check run
        uses: ./.github/workflows/steps/run-node-script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: ./.github/scripts
          script: update-check-run
          args: |
            --repository=${{ github.repository }} \
            --check_run_id=${{ needs.update.outputs.check-id }} \
            --status=completed \
            --conclusion=${{ steps.copy-runs.outputs.script-result }}
